name: flutter_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  deepgram_speech_to_text:
    path: ../../
  universal_file: ^1.0.0
  record: ^5.0.5
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.0.0
  file_picker: ^8.0.5
  win32: ^5.5.1 # https://github.com/miguelpruivo/flutter_file_picker/issues/1531

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
